source:
  image: debian:jessie
  command: bin/bash -c "while true; do echo 'Log'; sleep 1; done"

worker:
  build: .
  command: cloudwatch://logspout-cloudwatch
  hostname: demo
  environment:
    LOG_LEVEL: DEBUG
    AWS_REGION: us-west-2
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
